GET http://localhost:3000/api/users



POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "juanperez2",
  "email": "juanperez@example2.com",
  "password": "otroPassword123"
}



GET http://localhost:3000/api/users/1

###

PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
  "role": "admin"
}

DELETE http://localhost:3000/api/users/11


GET http://localhost:3000/api/events


POST http://localhost:3000/api/events
Content-Type: application/json

{
  "title": "Partido de Fútbol",
  "description": "Amistoso en el parque",
  "location": "Parque Central",
  "sportType": "fútbol",
  "dateTime": "2025-06-20T17:00:00Z",
  "capacity": 10,
  "creatorId": 1
}


GET http://localhost:3000/api/events/1


PUT http://localhost:3000/api/events/1
Content-Type: application/json

{
  "capacity": 12,
  "location": "Estadio Municipal"
}


DELETE http://localhost:3000/api/events/1
